### ISSUE TITLE
Fix clippy complaints

### ISSUE THREAD

**Issue by dtolnay** [toml-rs/toml-rs#139]
I tried running `cargo clippy` against the serde-upgrade branch and it flags 33 things.

**Comment by est31** [comment]
Fixed by #157

**Comment by ehuss** [comment]
I wouldn't say it's fixed, there are now over 100 warnings.

**Comment by NickHackman** [comment]
In #321 all Clippy Errors are fixed and one Warning remains

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
