### ISSUE TITLE
Don't buffer inline tables and arrays in memory when decoding

### ISSUE THREAD

**Issue by alexcrichton** [toml-rs/toml-rs#140]
Right now as a convenience when the parser hits an inline table or an array it'll buffer up all the values in an intermediate vector. We should defer this parsing if possible to the end and only keep spans into the original document.

The tricky part here is going to be handling multiline arrays, we at *least* need to walk through tokens to find a balanced delimiter but that involves parsing strings which can be a lot of work. Unsure what the best tradeoff is here.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
