### ISSUE TITLE
Verify crate with official ABNF

### ISSUE THREAD

**Issue by alexcrichton** [toml-rs/toml-rs#163]
There's an [official ABNF](https://github.com/toml-lang/toml/blob/master/toml.abnf) for TOML. I'd love to generate documents based on the ABNF and then verify that they parse correctly.

This is a pretty significant project, though!

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
