### ISSUE TITLE
Switch to infallible indexing (like serde_json)

### ISSUE THREAD

**Issue by killercup** [toml-rs/toml-rs#193]
[serde_json](https://github.com/serde-rs/json) implements `std::ops::Index` for its `Value` in a way that instead of panicking on unknown fields returns `Value::Null`. See [here](https://docs.rs/serde_json/1.0.2/serde_json/enum.Value.html#method.get) for more information. This is really nice and allows very concise code when dealing with JSON Values, and I'd love to add something similar to toml-rs.

But, **TOML does not have a `null` value.** So we can't copy the code/idea from serde_json as-is.

Do you think it'd make sense to introduce a new `ValueOrNull` type, which `<Value as Index>::index` returns, and that can deref to `Option<Value>`, but also implements `Index`, and the usual `as_*` methods from `Value`?

**Comment by alexcrichton** [comment]
Heh I also thought this was super slick of `serde_json` and then lamented that TOML doesn't have a null value. I'm not sure I can quite visualize what you're thinking, but I'm more than open to pursuing something here, it'd be quite nice!

**Comment by killercup** [comment]
Let me expand a bit. So, the goal is to allow code like

```rust
let data: toml::Value = toml::from_str(…);
let thingy = data["foo"]["bar"].as_str().unwrap();
```

And the ValueOrNull idea is basically just

```rust
impl Index for toml::Value {
  fn index(…) -> ValueOrNull {…}
}

enum ValueOrNull { Null, Value(toml::Value) }

impl Index for ValueOrNull {
  fn index(&self, idx: …) -> ValueOrNull {
    match &self {
        ValueOrNull::Null => ValueOrNull::Null,
        ValueOrNull::Value(val) =>  val[idx],
    }
  }
}

impl ops::Deref for ValueOrNull { target = Option<toml::Value> … }

impl ValueOrNull {
  // same as toml::Value methods
  fn as_bool(&self) -> Option<bool> {…}
  fn as_str(&self) -> Option<&str> {…}
  fn as_table …
}
```

Do you think this could work?

**Comment by alexcrichton** [comment]
I think the signature of `index` may thwart us, requiring `&'a T`, right?

**Comment by killercup** [comment]
Ah yes, this might be tricky. Maybe `-> &'a ValueOrNull<'val> where 'val:
'a`? That's probably still not compatible with Index though.

Alex Crichton <notifications@github.com> schrieb am Di. 27. Juni 2017 um
00:36:

**Comment by alexcrichton** [comment]
Worth trying!

**Comment by quadrupleslap** [comment]
Can I get similar behavior right now by using `Option::and_then`?

**Comment by reverland** [comment]
I have a question, how to gracefully handle panic here, one may have to check every time before indexes?

**Comment by sabitm** [comment]
is there any workaround / solution for this? need to handle panic on non-existent index

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
