### ISSUE TITLE
Fails to roundtrip various types

### ISSUE THREAD

**Issue by sp3d** [toml-rs/toml-rs#194]
I have the following test case:

Cargo.toml
```
[package]
name = "toml-bug"
version = "0.1.0"
authors = ["sp3d"]

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
sodiumoxide = "0.0.15"
```

src/main.rs
```
#[macro_use]
extern crate serde_derive;

extern crate toml;
extern crate sodiumoxide;

use sodiumoxide::crypto::box_::curve25519xsalsa20poly1305::*;

#[derive(Serialize, Deserialize, PartialEq)]
pub struct PubKey(PublicKey);

#[derive(Serialize, Deserialize, PartialEq)]
struct S { pubkey: PublicKey }

#[test]
fn test() {
	let (pubkey, _privkey) = gen_keypair();
	let s = S {pubkey};

	let encoded = toml::to_string(&s).unwrap();
	println!("encoded: {}", encoded);
	let s2 = toml::from_str(&*encoded).expect("failed to roundtrip");
	assert!(s == s2);
}

#[test]
fn test2() {
	let (pubkey, _privkey) = gen_keypair();

	let encoded = toml::to_string(&pubkey).unwrap();
	println!("encoded: {}", encoded);
	let pubkey2 = toml::from_str(&*encoded).expect("failed to roundtrip");
	assert!(pubkey == pubkey2);
}

#[test]
fn test3() {
	let (pubkey, _privkey) = gen_keypair();
	let pubkey = PubKey(pubkey);

	let encoded = toml::to_string(&pubkey).unwrap();
	println!("encoded: {}", encoded);
	let pubkey2 = toml::from_str(&*encoded).expect("failed to roundtrip");
	assert!(pubkey == pubkey2);
}
```

At present `test2` and `test3` panic with ` Error { inner: ErrorInner { kind: Wanted { expected: "a right bracket", found: "a comma" }`.

If I implement `deserialize_bytes` as follows, `test2` starts working but `test3` continues to give the same error. Am I on the right track here? Any guidance would be appreciated.

```
diff --git a/src/de.rs b/src/de.rs
index d5af272..5d0018d 100644
--- a/src/de.rs
+++ b/src/de.rs
@@ -248,10 +248,40 @@ impl<'de, 'b> de::Deserializer<'de> for &'b mut Deserializer<'de> {
         }
     }
 
+    fn deserialize_bytes<V>(
+        self,
+        visitor: V
+    ) -> Result<V::Value, Error>
+        where V: de::Visitor<'de>
+    {
+        let mut ret = Vec::new();
+
+        let at = self.tokens.current();
+        let value = self.value()?;
+        let out = match value {
+            Value::Array(v) =>
+                v.iter().fold(Ok(()), |state, inner| {
+                    if state.is_err() {
+                        return state
+                    };
+                    match inner {
+                        &Value::Integer(n) if n < 256 => { ret.push(n as u8); Ok(()) },
+                        &Value::Integer(_) => Err(self.error(at, ErrorKind::NumberInvalid)),
+                        _ => Err(self.error(at, ErrorKind::MixedArrayType)),
+                    }
+                }),
+            _ => Err(self.error(at, ErrorKind::Wanted {
+                    expected: "a byte array",
+                    found: "something else"/*self.token.describe()*/,
+                })),
+        };
+
+        return out.and_then(|()| visitor.visit_bytes(&*ret))
+    }
 
     forward_to_deserialize_any! {
         bool u8 u16 u32 u64 i8 i16 i32 i64 f32 f64 char str string seq
-        bytes byte_buf map struct unit newtype_struct
+        byte_buf map struct unit newtype_struct
         ignored_any unit_struct tuple_struct tuple option identifier
     }
 }
```

Thanks.

**Comment by sp3d** [comment]
I can reduce test3 (which still fails) to a simpler case not involving serde:

```
#[derive(PartialEq, Serialize, Deserialize)]
pub struct UsizeWrapper(usize);

#[test]
fn test4() {
	let lt = UsizeWrapper(4);

	let encoded = toml::to_string(&lt).unwrap();
	println!("encoded: {}", encoded);
	let lt2 = toml::from_str(&*encoded).expect("failed to roundtrip");
	assert!(lt == lt2);
}
```

I'll put together a PR for the fix for test/test2; I don't understand yet how to fix test3/test4. Do you think you could point me at the code relevant to [de]serializing tuple-structs?

**Comment by sp3d** [comment]
Ok, apparently this case is actually explicitly separated as newtype struct, and toml-rs doesn't support the more general forms of tuple structs. However, when I add code to the impl of `de::Deserializer` for `Deserializer` to handle newtype structs (such as the below), it fixes test3 while leaving test4 unchanged:

```
    fn deserialize_newtype_struct<V>(
        self,
        _name: &'static str,
        visitor: V
    ) -> Result<V::Value, Error>
        where V: de::Visitor<'de>
    {
        return visitor.visit_newtype_struct(self)
    }
```

In test4, the newtype struct serializes to just the string `4`. And it kind of makes sense that toml-rs refuses to deserialize that, since it's not a valid TOML document on its own. But the same should be true for the naked arrays serialized and deserialized in test2 and test3 (e.g. `[75, 33, 238, 90, 63, 60, 170, 120, 212, 143, 73, 18, 161, 210, 218, 110, 72, 72, 67, 229, 19, 31, 24, 209, 204, 144, 133, 92, 176, 227, 24, 101]`). So now I'm not sure what to do. If toml-rs should serialize values to valid TOML documents, then the *serialization* for "bytes" and newtype structs is wrong, and the deserialization should be written against a corrected serialization, not the present one.

Any thoughts?

**Comment by alexcrichton** [comment]
@sp3d that addition of handling newtype structs looks good to me! I'm not sure I follow the business with "test4" though, mind elaborating?

**Comment by sp3d** [comment]
At this point I don't think that either of the impls I posted above should be included in the library, because they deserialize strings which are not themselves valid TOML documents (key-value pairs and tables). However, I'm confused by the fact that these strings are *currently* produced by toml-rs when asked to serialize bytevectors and tuple-structs. Shouldn't toml-rs always serialize a value to a valid TOML document?

Test4 is the test that made me realize this problem, as it simply serializes to "4" at the moment, which is very clearly not a TOML document (which, per the spec and the general setup of toml-rs's deserializer, consist of key-value pairs and tables, but not standalone values).

It seems like the right way to address this may involve separate traits for top-level and value-level (as in, right-hand side of a key-value pair) serialization, since a given Rust value may need to be serialized either standalone or as part of another value.

**Comment by alexcrichton** [comment]
The thinking was that you could serialize any toml-like-value, but you can only parse toml documents. I wouldn't mind changing the parser to *also* accept toml-like values so you could parse just a toml string or number instead of only being able to parse out tables.

**Comment by sp3d** [comment]
I don't really know of a use case for serializing to "toml-like" strings, except as part of serializing to a complete TOML document. I'd think it would make more sense to make the distinction between top-level and key-value-rhs serialization modes internally to toml-rs, but as a user of the library it's much simpler and more robust to always get valid TOML documents out and accept the same.

**Comment by alexcrichton** [comment]
Yeah I'm fine tiehr way!

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
