### ISSUE TITLE
Add `from_reader` method

### ISSUE THREAD

**Issue by pbzweihander** [toml-rs/toml-rs#215]
Like serde_json, it will be nice if we have `from_reader`.

If we don't have one...
```rust
use std::fs::File;
use std::io::Read;

let mut file = File.open(path)?;
let mut content = String::new();
file.read_to_string(&mut content)?;
let some_struct: SomeStruct = toml::from_str(&content)?;
```

But if we have one...
```rust
use std::fs::File;

let file = File.open(path)?;
let some_struct: SomeStruct = toml::from_reader(&file)?;
```

I'm just beginner of rust, so I don't have enough ability to make it myself and make a pull request. But if anyone can make, codes will be cleaner like above.

**Comment by alexcrichton** [comment]
Thanks for the report! Right now there's no actual underlying method of doing this *other* than just reading it entirely to a string, but having that done in a helper function seems fine to me!

**Comment by RazerM** [comment]
What would we do about the error from `read_to_string`? We can't just add `Io(io::Error)` to `toml::de::ErrorKind` because `Clone` isn't implemented for `io::Error`.

**Comment by alexcrichton** [comment]
I think it's probably ok to throw it in something like an `Arc` to make it clone-able

**Comment by orlp** [comment]
@alexcrichton 

Any update on this?

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
