### ISSUE TITLE
Formatting of map after struct

### ISSUE THREAD

**Issue by qzed** [toml-rs/toml-rs#219]
There is no empty line inserted when a map is serialized after a struct. This behaviour is inconsistent to the formatting of other table-like structures, i.e. structs and arrays. It's not a big deal as it does not violate the TOML specification, but it may impede readability.

### Minimal Example:
```rust
extern crate serde;
#[macro_use] extern crate serde_derive;
extern crate toml;

use std::collections::HashMap;


#[derive(Serialize, Deserialize)]
struct Foo {
    bar: Bar,
    baz: HashMap<String, Bar>,
}

#[derive(Serialize, Deserialize)]
struct Bar {
    foo: u32
}

fn main() {
    let mut baz = HashMap::new();
    baz.insert("a".into(), Bar { foo: 0 });

    let foo = Foo {
        bar: Bar {
            foo: 42,
        },
        baz: baz,
    };

    println!("{}", toml::to_string_pretty(&foo).unwrap());
}
```

#### Actual Output:
```toml
[bar]
foo = 42
[baz.a]
foo = 0
```

#### Expected Output:
```toml
[bar]
foo = 42

[baz.a]
foo = 0
```

Swapping the `bar` and `baz` members of `Foo` produces an expected result.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
