### ISSUE TITLE
Custom error with position

### ISSUE THREAD

**Issue by EPashkin** [toml-rs/toml-rs#226]
I have complex struct with custom `serde::Deserialize`.
In its implementation sometime I return custom error (`E::custom("error text")`),
The problem is that the error does not show where in the file it occurred:
`Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "error text", ... } }`
There way to create error from current position of deserializer?

**Comment by alexcrichton** [comment]
This isn't currently possible, but I'd be totally down for creating a method to do so!

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
