### ISSUE TITLE
Please provide an example for modifying and serializing a config file back to disk

### ISSUE THREAD

**Issue by axos88** [toml-rs/toml-rs#228]

**Comment by alexcrichton** [comment]
Thanks for the report! One of the caveats with this library, however, is that this isn't that well supported because formatting is not preserved. Is that a requirement for you though?

**Comment by axos88** [comment]
Nope, in my use case the config file is intended to be read and written by the code only.

I worked it out in the end, might provide a PR next week.

**Comment by alexcrichton** [comment]
Ok great!

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
