### ISSUE TITLE
Duplicate keys not rejected when deserializing into a type

### ISSUE THREAD

**Issue by pietroalbini** [toml-rs/toml-rs#230]
While duplicate keys are correctly rejected when deserializing into a `toml::Value`, deserializing into any other type accepts them (and that's against the spec).

```rust
let content = "a = 1\na = 2";
    
assert!(toml::from_str::<HashMap<String, i32>>(content).is_ok());
assert!(toml::from_str::<toml::Value>(content).is_err());
```

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
