### ISSUE TITLE
 toml::from_str can not parse valid u64 integer.

### ISSUE THREAD

**Issue by fragrans** [toml-rs/toml-rs#256]
Here is the test code :
```
extern crate toml;

#[macro_use]
extern crate serde_derive;

#[derive(Debug, Serialize, Deserialize)]
struct T {
    i:u64
}

fn main() {
    let mut i = 1u128;
    
    loop {
        if i > std::u64::MAX as u128 { break }
        let t = T {
            i: i as u64
        };

        println!("u64: {}", t.i);
        
        let toml_s = toml::to_string(&t).unwrap();
        
        let new_t = toml::from_str::<T>(&toml_s);
        if new_t.is_err() {
            println!("{:?}", new_t);
            println!("toml_s: {}", toml_s);
            println!("t.i: {}", t.i);
            println!("max: {}", std::u64::MAX);
        }
        i = i * 10;
    }
}
```
Here is the result. 

```
u64: 1
u64: 10
u64: 100
u64: 1000
u64: 10000
u64: 100000
u64: 1000000
u64: 10000000
u64: 100000000
u64: 1000000000
u64: 10000000000
u64: 100000000000
u64: 1000000000000
u64: 10000000000000
u64: 100000000000000
u64: 1000000000000000
u64: 10000000000000000
u64: 100000000000000000
u64: 1000000000000000000
u64: 10000000000000000000
Err(Error { inner: ErrorInner { kind: NumberInvalid, line: Some(0), col: 4, message: "", key: [] } })
toml_s: i = 10000000000000000000

t.i: 10000000000000000000
max: 18446744073709551615
```
see, 10000000000000000000 is less than u64 max: 18446744073709551615
![image](https://user-images.githubusercontent.com/102768/43938254-2f198354-9c95-11e8-902c-13ef32ea2c5e.png)

Is this a bug or not?

**Comment by fragrans** [comment]
But, I am using u64.
<hr>

![image](https://user-images.githubusercontent.com/102768/44513423-e4c04300-a6ef-11e8-8840-cb07c8d03104.png)

**Comment by dtolnay** [comment]
It looks like integer deserialization always uses an i64 even if not deserializing to toml::Value. This is a bug. https://github.com/alexcrichton/toml-rs/blob/0.4.6/src/de.rs#L815

**Comment by Lancern** [comment]
Are there any plans or WIP to solve this issue? Maybe I can help craft a patch.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
