### ISSUE TITLE
How to serialize to inline table vs. dotted table?

### ISSUE THREAD

**Issue by maackle** [toml-rs/toml-rs#265]
It seems that nested Tables are always serialized to dotted tables. e.g.:

```rust
let in_string = "[dependencies]\nhdk = { git = \"https://github.com/foo/bar\", branch = \"develop\" }"
let val = toml::from_str::<Value>(in_string)?;
println!("{:?}", toml::to_string(&val));
```

Even though the input string is an inline table, the output string uses a dotted table.

Is there no way to specify inline table when serializing?

**Comment by alexcrichton** [comment]
Currently this crate unfortunately doesn't support a lot of control over serialization and formatting, it just guarantees it emits *some* valid toml document, but not necessarily the prettiest

**Comment by swalladge** [comment]
Support for serializing inline tables would be great, because I suspect that is why I'm getting a `ValueAfterTable` error when serializing an object like:

```
#[derive(Deserialize, Serialize, Debug)]
#[serde(untagged)]
pub enum StringOrCmd {
    S(String),
    Cmd { cmd: Vec<String> },
}

#[derive(Deserialize, Serialize, Debug)]
pub struct BackendConfig {
    pub client_id: StringOrCmd,
    pub client_secret: StringOrCmd,
}

#[derive(Deserialize, Serialize, Debug)]
pub struct Config {
  backend: BackendConfig,
}
```

This should serialize to something like:

```
[backend]
client_id = { cmd = ["cat", ".clientid"] }
client_secret = "somesecret"
```

But becomes invalid TOML if not using inline table format:

```
[backend]

[backend.client_id]
cmd = ["cat", ".clientid"]

# oops!
client_secret = "somesecret"
```

The solution would be either supporting inline tables or using extra logic to ensure all literal types under a table are written out before any nested table types.

**Comment by DianaNites** [comment]
I just got hit by that `ValueAfterTable` problem and it'd be really nice if it worked.

I'm parsing perfectly valid toml and then can't write it out and thats no fun.

**Comment by swalladge** [comment]
Just for reference, [cargo-edit][1] uses [toml_edit][2] for parsing and writing cargo.toml files. Could be useful to see how they do it for anyone planning on implementing this for toml-rs.

[1]: https://github.com/killercup/cargo-edit
[2]: https://github.com/ordian/toml_edit

**Comment by gabbifish** [comment]
I'm definitely on team "would love to have an inline table serialization option!" here :)

**Comment by deg4uss3r** [comment]
:+1: Hitting this issue with `cargo-outdated` when trying to format `Cargo.toml` for `cargo` API. This causes interference with the `namespaced-features` feature.

**Comment by 89z** [comment]
https://github.com/alexcrichton/toml-rs/issues/406

**Comment by Iron-E** [comment]
I don't want to be one of those people who beats a dead horse, but I would like to show a potential use case for such a feature. Currently I have some structures that I want to let a user edit during runtime that come out a little unreadable:

```toml
# Edit your contact information, or add any as necessary

[value."LABEL ME 1"]
type = 'Address'

[value."LABEL ME 1".content]
name = 'Earth'

[value."LABEL ME 2"]
type = 'Email'
content = 'An email address. E.g. `foo@gmail.com`'

[value."LABEL ME 3"]
type = 'Phone'
content = 'A phone number. E.g. `600-555-5555`'
```

I would like that to look like this, which would probably be easier to read:

```toml
# Edit your contact information, or add any as necessary

[value]
"LABEL ME 1" = {type='Address', content={name='Earth'}}
"LABEL ME 2" = {type='Email', content='An email address. E.g. `foo@gmail.com`'}
"LABEL ME 3" = {type='Phone', content='A phone number. E.g. `600-555-5555`'}
```

Or anything else that keeps the label in one place (my main concern is a user forgetting to edit the label in the `content` section, or putting a typo there).

**Comment by timabell** [comment]
There's a round-trip test of an inline table at https://github.com/alexcrichton/toml-rs/blob/60b874308e6792a73cc00517a60bbef60a12e3cc/test-suite/tests/valid/example-v0.4.0.toml#L34-L46= which makes me think this must be possible somehow with the right structures. Maybe it only works with the toml-rs internal types at the moment and not with types defined outside the toml-rs library.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
