### ISSUE TITLE
Support for u128, i128 integer types 

### ISSUE THREAD

**Issue by AregevDev** [toml-rs/toml-rs#266]
Pretty self-explained, serde is already support them, will be nice to see them in the TOML format

**Comment by alexcrichton** [comment]
Thanks for the report! Can you gist an example of what doesn't work to have a good test case to check in?

**Comment by AregevDev** [comment]
Sure thing, will be done when I will be back

**Comment by AregevDev** [comment]
https://gist.github.com/AregevDev/79dcde42ee06c23d3f5a892596001667
There you go!

**Comment by AregevDev** [comment]
Any news?

**Comment by AregevDev** [comment]
I serialized a struct with two 128 bit integers successfully but deserializing them is the tricky part

**Comment by AregevDev** [comment]
Built from source and modified a little

**Comment by AregevDev** [comment]
Solved, I can deserialize i/u128 which are not overflowing the i/u64::max_value() perspectively

**Comment by nullchinchilla** [comment]
I'd like to bump this issue a bit, since it's quite a critical feature for my use case.

**Comment by TheDarkula** [comment]
I opened a pull request to add this functionality: #445

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
