### ISSUE TITLE
Serialize doc comments

### ISSUE THREAD

**Issue by swfsql** [toml-rs/toml-rs#274]
Similarly to the [structopt](https://github.com/TeXitoi/structopt) behavior, which uses doc `///` comments to generate the *help text* for some parameter/struct/etc, could `toml-rs` optionally use doc comments to print such doc comments as a *TOML comment* in the serialized TOML file?

TOML supporting commentaries is really a plus!
I'd be using it for default TOML configuration generation, and it would be awesome if those were to have default commentaries as well.

**Comment by JohnScience** [comment]
It would be a great feature

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
