### ISSUE TITLE
Serialize integer as hexadecimal/octal/binary with prefix

### ISSUE THREAD

**Issue by n3vu0r** [toml-rs/toml-rs#285]
Is there a way to serialize an integer as hexadecimal/octal/binary with 0x/0o/0b prefix?

**Comment by alexcrichton** [comment]
Currently there's not unfortunately, this crate doesn't provide a lot of options to customize the serialization at this time. Ideally though it'd all be in this crate!

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
