### ISSUE TITLE
Document `preserve_order` feature

### ISSUE THREAD

**Issue by ehuss** [toml-rs/toml-rs#300]
Should probably go in top-level module docs.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
