### ISSUE TITLE
Fails to (de)serialized enums with different variant types

### ISSUE THREAD

**Issue by axos88** [toml-rs/toml-rs#302]
```
enum E {
  Foo,
  Bar(u32)
}
```

Fails to serialize / deserialize correctly. Probably related to #264 #267.

**Comment by axos88** [comment]
`Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: "invalid type: unit variant, expected string only", key: ["e", "bar"] } }`

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
