### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by tomansill** [toml-rs/toml-rs#306]
The current documentation appears to be bit old and sparse. I've tried following the example as outlined in documents and `examples/`, I could not get the code to compile. After some digging around and asking around on Rust-lang discord server, it turns out that I need to add the following to `[dependencies]` to `Cargo.toml`:

```rust
serde = {version "...", features = ["derive"]}
```

Then add `use serde::Deserialize` to your code that will use `#[derive(Deserialize)]` on your structs.

It would be nice if the documentation is updated to reflect this change.

**Comment by JayKickliter** [comment]
Thanks. I just got stuck at this exact spot.

**Comment by David-OConnor** [comment]
Need a real-world example of parsing a `TOML` file.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
