### ISSUE TITLE
example  enum_external   have  "ArrayMixedType" error

### ISSUE THREAD

**Issue by zuowenjian** [toml-rs/toml-rs#345]
when i add code for   example  enum_external : 
``` rust
    let decoded: Config = toml::from_str(toml_str).unwrap();
    println!("{:#?}", decoded);
    let data = toml::to_string(&decoded).unwrap() ;  //add
    println!("{:?}", data);   //add
```
have error :
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ArrayMixedType', src/libcore/result.rs:1084:5

```

**Comment by alexcrichton** [comment]
Thanks for the report! Could you gist a complete reproduction to ensure that all the code necessary to reproduce is here?

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
