### ISSUE TITLE
Lists of Option generate malformed TOML with no error

### ISSUE THREAD

**Issue by LPGhatguy** [toml-rs/toml-rs#356]
Given this code snippet:

```rust
use toml; // 0.5.3
use serde::Serialize; // 1.0.101

#[derive(Serialize)]
struct Container {
    values: Vec<Option<String>>,
}

fn main() {
    let serialized = toml::to_string(&Container {
        values: vec![
            Some("Hello".to_owned()),
            None,
            Some("World".to_owned())
        ],
    }).unwrap();
    
    println!("{}", serialized);
}
```

We get an output of:

```toml
values = ["Hello"
```

This is obviously not well-formed TOML. It looks like the serializer gives up when encountering something that needs be an empty value and bails on the rest of the serialization.

Notably, this means that the toml crate can't parse this file anymore, resulting in data corruption. ☹️ 

Since TOML has no concept of null, I'm unsure what this crate should do. This should be reported as an error at least, I think.

**Comment by ehuss** [comment]
I looked at other libraries for other languages (like Python, Ruby, C, and Go), and they either skip none/null/nil values, or raise an error, it isn't very consistent.  

I don't have a strong opinion either way.  I think an error would be the safer choice.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
