### ISSUE TITLE
Serialization issue: skips array-like field

### ISSUE THREAD

**Issue by Ploppz** [toml-rs/toml-rs#371]
The problematic type in question is `Region` from `rusoto_core`. It can be deserialized successfully from a TOML array like for example `s3_region = ["eu-west-1", ]`, but serialization does not work.

Minimal example to reproduce the issue:

`src/main.rs`
```
use rusoto_core::region::Region;
use std::path::PathBuf;
use serde::{Serialize, Deserialize};


fn main() {
    let cfg = Config::default();
    println!("Config ok:\n\n{}", cfg.to_toml_string());
    cfg.validate();
}

#[derive(Clone, Debug, Serialize, Deserialize, Default)]
pub struct Config {
    pub s3_region: Region,

}
impl Config {
    pub fn to_toml_string(&self) -> String {
        toml::value::Value::try_from(&self).unwrap().to_string()
    }
    pub fn validate(&self) {
        let s = toml::value::Value::try_from(&self).unwrap().to_string();
        let cfg = toml::de::from_str::<Config>(&s).unwrap();
        println!("{:?}", cfg.s3_region)

    }
}
```

`Cargo.toml`
```
[package]
name = "a"
version = "0.1.0"
authors = ["Erlend Langseth <3rlendhl@gmail.com>"]
edition = "2018"

[dependencies]
toml = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
rusoto_core = "0.42.0"
```

Output:
```
Config ok:


thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, at: None, message: "missing field `s3_region`", key: [] } }', src/libcore/result.rs:1165:5
stack backtrace:
......
```

**Comment by ehuss** [comment]
The general issue here is that TOML doesn't support `None` as a value.  Your example is trying to serialize `("us-east-1", None)`, but there is nothing TOML can place in the array to represent None.

Unfortunately improving the error message here might be difficult.  The `Value` map serialization code checks for None errors in order to skip over map keys whose value is None (thus the "missing field" error).  It doesn't understand that the serialization failed *within* the value, which should be a hard error.

If you don't serialize via `Value` (using `toml::to_string`), it will unfortunately serialize incorrectly (#356).

**Comment by Ploppz** [comment]
Thanks for the explanation. It seems like deserialization works with null values since it works on `s3_region = ["eu-west-1", ]`. Could it not produce the same text upon serialization?

**Comment by ehuss** [comment]
It could, but that's the question in #356 if that's the right behavior in all (or majority) of cases.  I could see how filtering None values could lead to subtle bugs.  On the other hand, it would be convenient for situations like this.

Perhaps one of the serde experts would have guidance on how to handle `serialize_none` in a sequence for a data format that does not support None/null values?  Should it silently skip the value, or raise an error?

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
