### ISSUE TITLE
JSON -> TOML with null values causes an UnsupportedType Error

### ISSUE THREAD

**Issue by axos88** [toml-rs/toml-rs#374]
Currently if a json object contains fields with null values, `toml::Value::try_from(json)` causes an UnsupportedType Error, where json is:

```
Object({"directory": Null, "notification_email": Null, "common_names": Array([String("a"), String("b"), String("c"), String("d")]), "user_key_path": Null, "challenge_path": Null, "success_action": String("Exit"), "error_action": String("RetryInTenMinutes"), "poll_time_secs": Number(604800), "ttl_secs": Number(2592000)})
```

According to the spec, these fields should be simply "left out", and the following toml generated:

```
  common_names = ["a","b","c","d"]
  success_action = "Exit"
  error_action = "RetryInTenMinutes"
  poll_time_secs = 604800
  ttl_secs = 2592000
```

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
