### ISSUE TITLE
impl TryFrom<&str> for Value

### ISSUE THREAD

**Issue by Kixunil** [toml-rs/toml-rs#375]
I think it'd be useful to provide `impl TryFrom<&str> for Value` consider this scenario:

```rust
fn do_something_with_toml<T: TryInto<toml::Value>(value: T) -> Result<(), <T as TryInto>::Error> {
let toml = value.try_into();
// do something with toml
}
```

This would be a really neat signature that would allow passing `&str`, but also `Value`, if the caller happens to already have it deserialized.

**Comment by brightly-salty** [comment]
I'd be willing to implement this and submit a PR if it would be accepted.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
