### ISSUE TITLE
Preserve order on map removal

### ISSUE THREAD

**Issue by anowell** [toml-rs/toml-rs#380]
The switch from linked-hash-map to indexmap seems to have broken order preservation during removal (when using `preserve_order`). 

As of [this indexmap PR](https://github.com/bluss/indexmap/pull/99), indexmap has a `shift_remove` and `swap_remove`, but [as documented](https://docs.rs/indexmap/1.3.2/indexmap/map/struct.IndexMap.html#method.remove), `remove` uses `swap_remove`. 

This seems like a regression or otherwise breaking change to toml `0.5.4`, as `LinkedHashMap` does preserve order during removal via `remove`. Here's a [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=83b83f7324b50ad57b34117356820d04) showing the difference.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
