### ISSUE TITLE
Missing key and line number information on parse error.

### ISSUE THREAD

**Issue by tcanabrava** [toml-rs/toml-rs#383]
Code:

```
 #[serde(Deserialize)]
 struct Test {
       some_sequence : Vec<String>
}
```

Toml File:

`some_sequence = false`

Loaded as:
```
let contents =
        std::fs::read_to_string(some_file).expect("Something went wrong reading the file");

    let kconfig_init: Test =
        toml::from_str(&contents).expect("Error parsing the toml file");
```

Error produced:

> Error { inner: ErrorInner { kind: Custom, line: Some(0), col: 0, at: Some(0), message: "invalid type: boolean `true`, expected a sequence", key: [] } }

Expected: 
```

Something in the lines of:
"The value for the element 'some_sequence' has invalid type. we found a `true` but we expected a `sequence`, line 1 col 10"
```

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
