### ISSUE TITLE
toml::ser::tables_last does not work correctly with empty vectors

### ISSUE THREAD

**Issue by jbethune** [toml-rs/toml-rs#384]
# Background

The TOML representation for arrays is different depending on whether or not they are empty:

```
foo = [] # empty array, all in one line
```
compared to
```
[[foo]] # array with (at least) one element. Needs a dedicated section
bar = 42
```
# Problem
It seems that the serializer "promotes" empty arrays to single values while non-empty arrays are still rendered as multiline text. This is a problem, because such single values are supposed to be separate from the more complex data types. The macro `toml::ser::tables_last` is supposed to separate fields based on their types (primitive, array, table). But right now this separation does not take into account if an array value is empty or not.

# Code demonstrating the issue

```
extern crate serde;
extern crate toml;

use std::collections::HashMap;

use serde::{Serialize, Deserialize};
use toml::to_string_pretty;

#[derive(Serialize, Deserialize)]
struct Foo {
    //#[serde(serialize_with = "toml::ser::tables_last")]
    a: Vec<HashMap<String,usize>>,
    //#[serde(serialize_with = "toml::ser::tables_last")]
    b: Vec<HashMap<String,usize>>,
    //#[serde(serialize_with = "toml::ser::tables_last")]
    c: Vec<HashMap<String,usize>>,
}

fn main() {

    let mut f = Foo{
        a: Vec::new(),
        b: Vec::new(),
        c: Vec::new(),
    };

    let mut hm = HashMap::new();
    hm.insert( "hello".to_string(), 42 as usize );
    f.a.push( hm );

    let mut hm = HashMap::new();
    hm.insert( "world".to_string(), 42 as usize );
    //f.b.push( hm ); // uncomment this line to make things run again

    let mut hm = HashMap::new();
    hm.insert( "again".to_string(), 42 as usize );
    f.c.push( hm );

    let res = to_string_pretty( &f );
    match res {
        Ok( v ) => println!( "success: {}", v ),
        Err( e ) => println!( "failure: {}", e )
    }
}
```
This code produces the error message `failure: values must be emitted before tables`. The vector `f.b` is empty and because it is in the middle of the struct, the error is triggered.

**Comment by jbethune** [comment]
I made a mistake:
```
//#[serde(serialize_with = "toml::ser::tables_last")]
```
I overlooked that these lines are commented out. I was testing different things and forgot to reenable them again (and my syntax highlighting is the same for annotations and comments). I also now understand that `toml::ser::tables_last` is only meant for HashMap-like data structures and not for arrays. But arrays can suffer from the same ploblem as hash-tables when their contents are complex as illustrated by the code above.

The code below is an updated example that demonstrates the problem:
```
extern crate serde;
extern crate toml;

use serde::{Serialize, Deserialize};
use toml::to_string_pretty;


#[derive(Serialize, Deserialize)]
struct Foo { // I cannot use tables_last here, because it is a vector
    a: Vec<Bar>,
    b: Vec<Bar>,
    c: Vec<Bar>,
}

#[derive(Serialize, Deserialize, Clone)]
struct Bar {
    a: usize,
    b: usize,
}

fn main() {

    let mut f = Foo{
        a: Vec::new(),
        b: Vec::new(),
        c: Vec::new(),
    };

    let bar = Bar{ a: 1, b: 2 };

    f.a.push( bar.clone() ); // this line can be removed without issues
    f.b.push( bar.clone() ); // this line cannot be removed
    f.c.push( bar.clone() ); // this line cannot be removed

    let res = to_string_pretty( &f );
    match res {
        Ok( v ) => println!( "success: {}", v ),
        Err( e ) => println!( "failure: {}", e )
    }
}
```
This code does not use `tables_last` but it probably needs something like it. It's also interesting to see that I can leave `f.a` empty, but not `f.b`, `f.c`. At least that's my observation on my system.

**Comment by jbethune** [comment]
I'm using `#[serde(skip_serializing_if="std::vec::Vec::is_empty" )]` for now as a workaround.

**Comment by D1plo1d** [comment]
I'm having this same issue with empty `Vec`s. While the `skip_serializing_if` workaround fixed it I don't imagin this was expected behaviour for toml. Would it be possible to re-open this issue in the interest of a fix landing in`toml-rs`?

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
