### ISSUE TITLE
Extract a self-contained toml_lexer crate

### ISSUE THREAD

**Issue by Veetaha** [toml-rs/toml-rs#394]
Hi, I'd like to use your `lexer` in the implementation of the [language server for Cargo.toml](https://github.com/matklad/tom).
This is the thing we have already done with `rustc_lexer` (i.e. `rustc_lexer` is shared between `rustc` and `rust-analyzer`), so I'd like to do a similar thing here too.

@alexcrichton I know you are busy, but I am willing to help. If I restructure your repo to a cargo workspace with `crates/toml_lexer` and `crates/toml`, such that you can publish the lexer, would you accept this change? If you don't have time for publishing or even maintaining this crate, please consider giving the maintenance rights to any contributor you trust here, or me :D

**Comment by alexcrichton** [comment]
I'd be happy to have such a crate extracted here! In theory the code is already organized to make this relatively easy to happen, but yeah I don't mind publishing a second crate.

**Comment by Veetaha** [comment]
Hmm, now that I've tried to extract the lexer, I see that it has not the api I want.
What I want is something like
```rust
fn next(&mut self) -> Option<((Span, Token), Option<Error>)>
```
i.e. error-resilient tokenizer, where it doesn't bail on the first invalid hex escape or newline in a string etc., but does produce a token even if it is invalid, and in the worst case returns `Unknown` token just like [`rustc_lexer` does](https://github.com/rust-lang/rust/blob/45127211566c53bac386b66909a830649182ab7a/src/librustc_lexer/src/lib.rs#L126-L127).
But your tokenizer has the following signature:
```rust
fn next(&mut self) -> Result<Option<(Span, Token)>, Error>;
```
so it stop lexing right after the first error is detected which is not acceptable in my case.

Of course, error-resilient lexer is a superset of error-reluctant, i.e. you can implement the error-resilient lexer and make a wrapper around it to make it error-reluctant:
```rust
impl ErrorReluctantLexer {
    fn next(&mut self) -> Result<Option<(Span, Token)>, Error> {
        let ((span, token), error) = self.error_resilient_lexer.next()?;
        error?;
        Ok(Some((span, token)))
    }
}
```
But I doubt that this implementation suits `toml-rs`. Like it will slightly decrease the performance and error-reluctant parsing is what `toml-rs` feature is, so I have a bad time feeling about going this way.
What do you think, @alexcrichton ?

**Comment by alexcrichton** [comment]
Hm well so it makes sense that as-is it's not perfect for everyone's use case. That being said I suspect a PR and some small changes would be all that's necessary. The peformance doesn't really matter and it's easy to tweak the interfaces.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
