### ISSUE TITLE
Better syntax errors for toml macro

### ISSUE THREAD

**Issue by clarfonthey** [toml-rs/toml-rs#403]
Ideally, this would be implemented as a `proc_macro` so it can provide better syntax errors. The existing macro system isn't as robust and so syntax errors tend to be a bit cryptic.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
