### ISSUE TITLE
Custom Deserializer for Foreign Type

### ISSUE THREAD

**Issue by creese** [toml-rs/toml-rs#411]
I'm creating an app that takes input from a file. The file will be edited by hand.

Here is an example:
```
foo = 7300
bar = "0x4563918244f40000"
```

This is the struct:
```
use serde::Deserialize;
use web3::types::U256;

#[derive(Deserialize)]
struct FooBar {
    foo: U256,
    bar: u32,
}
```
Here, `U256` is a foreign type. It isn't part of my code base.

This works, but there are two problems. First, `foo` is scaled quantity. It represents "7.3 percent". Second, `bar = "0x4563918244f40000"` is a more than I really want to type.

I would rather do this:
```
foo = "7.3" # implied conversation
bar = "5.0" # implied conversation
```

How can this be achieved?

**Comment by alexcrichton** [comment]
I think this is probably best achieved with Serde glue rather than anything specific to this crate, I'd recommend browsing serde.rs and seeing if any of the attributes work for you?

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
