### ISSUE TITLE
Prefix error context

### ISSUE THREAD

**Issue by mahkoh** [toml-rs/toml-rs#413]
Consider the following input:

```toml
listen_addr = [
    "[::]:8080",
    "abc:8080",
    "unix:abc",
]
```

which results in the following error message:

```
cannot parse `abc:8080`: failed to lookup address information: No address associated with hostname
```

If the Error is formated with `{}` we get the following output:

```
cannot parse `abc:8080`: failed to lookup address information: No address associated with hostname for key `listen_addr` at line 1 column 1
```

where it is unclear what the `for` even refers to.

Please add the option to format errors as follows:

```
at line 1 column 1: at key `listen_addr`: cannot parse `abc:8080`: failed to lookup address information: No address associated with hostname
```

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
