### ISSUE TITLE
std::time::Duration treated as a table during serialization

### ISSUE THREAD

**Issue by cirego** [toml-rs/toml-rs#415]
I ran into an issue serializing structs that contain a `std::time::Duration` field. Here is a sample struct that fails to serialize:

```rust
#[derive(Clone, Debug, Deserialize, Serialize)]
struct DefaultQuery {
    #[serde(deserialize_with = "deser_duration_ms")]
    sleep_ms: Duration,
    #[serde(default)]
    group: Option<String>,
}
```

I got the following error: `values must be emitted before tables`. It works if we change the ordering of the fields to put `sleep_ms` last:

```rust
#[derive(Clone, Debug, Deserialize, Serialize)]
struct DefaultQuery {
    #[serde(default)]
    group: Option<String>,
    #[serde(deserialize_with = "deser_duration_ms")]
    sleep_ms: Duration,
}
```

Adding `serialize_with = "toml::ser::tables_last"` does not work, as `std::time::Duration` cannot be converted to an iterator:
```

error[E0271]: type mismatch resolving `<&std::option::Option<std::time::Duration> as IntoIterator>::Item == (_, _)`
    --> src/peeker/src/args.rs:359:83
     |
359  |     #[serde(default, deserialize_with = "deser_duration_ms_opt", serialize_with = "toml::ser::tables_last")]
     |                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^ expected tuple, found reference
     | 
    ::: /home/chris/github/alexcrichton/toml-rs/src/ser.rs:1584:25
     |
1584 |     &'a I: IntoIterator<Item = (K, V)>,
     |                         ------------- required by this bound in `tables_last`
     |
     = note:  expected tuple `(_, _)`
             found reference `&std::time::Duration`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0271`.
error: could not compile `peeker`

To learn more, run the command again with --verbose.
```

Happy to provide more details if they would help!

Extra notes:

I was able to discover this issue quickly with the following patch, as the error message doesn't indicate which data structure emitted tables before values:

```
diff --git a/src/ser.rs b/src/ser.rs
index e115541..414149f 100644
--- a/src/ser.rs
+++ b/src/ser.rs
@@ -461,6 +461,7 @@ impl<'a> Serializer<'a> {
                 key,
             } => {
                 if table_emitted.get() {
+                    println!("{:?}: {:?}", parent, key);
                     return Err(Error::ValueAfterTable);
                 }
                 if first.get() {
@@ -736,6 +737,7 @@ impl<'a> Serializer<'a> {
                 table_emitted,
                 ..
             } => {
+                println!("{:?}: {:?}", parent, key);
                 table_emitted.set(true);
                 let first = self.emit_key_part(parent)?;
                 if !first {
```

This implies that something is treating `std::time::Duration` objects as tables?

**Comment by ehuss** [comment]
Can you explain more what the expectations are?

Serde treats Duration as a table, like:

```toml
[sleep_ms]
secs = 1
nanos = 0
```

The TOML serializer does not support having tables before values, so you'll need to move it towards the end of the struct.  Or define a custom serializer that emits the Duration as a non-table format.

**Comment by cirego** [comment]
Eric Huss! I have not seen your name in a long time! I hope you're doing well!

I do see that Duration is being treated as a table. Part of the confusion came from a custom deserializer to convert a single "ms" String to a Duration but there was no serializer to convert it back.

Moving Duration to the end of the struct does indeed solve our issue. I think the behavior here is acceptable, but perhaps  the error message could be improved? Otherwise, I think this issue can be closed, as Duration is indeed a Table.

**Comment by ehuss** [comment]
Oh, hey Chris!  Fancy running into you here, it's been a long time!  Hope you're doing well, too!

Yea, the error messages can be a little rough sometimes, particularly with complex serde things.  I'm not sure if it can be easily improved, but I don't mind leaving it open.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
