### ISSUE TITLE
Add deserialize-datetime-as-string feature flag

### ISSUE THREAD

**Issue by not-my-profile** [toml-rs/toml-rs#423]
The `Deserializer` of this crate deserializes TOML datetimes as a map with a magic string, so e.g. `2021-04-03` becomes `{"$__toml_private_datetime" = "2021-04-03"}`. While the serializer of this crate catches these magic strings and converts them back into TOML datetimes (which is apparently necessary because serde provides no way to cleanly communicate types outside of its datamodel, see serde-rs/serde#1643), serializers from other crates obviously do not know about this magic string, resulting in it becoming part of their output if they are used with this crate.

I therefore propose the introduction of an optional `deserialize-datetime-as-string` feature flag (which would be disabled by default). If enabled this flag would make the `Deserializer` yield datetimes as strings instead of maps, making it for example easy to convert TOML to JSON without risking the leaking of this magic string.

If you think this is a good idea, I'd be happy to work on a PR.

Relevant comments in the code:

https://github.com/alexcrichton/toml-rs/blob/b1417006df376e6c406bff43740dd11aa7ef744e/src/datetime.rs#L37-L44

**Comment by ehuss** [comment]
Thanks for the report!  I think this sounds like a duplicate #159 maybe?  I think there is some discussion there on how to implement datetime deserialization.  I don't think a feature flag is appropriate since it would change the interface of the type. Maybe some of the suggestions in #159 could be explored?

**Comment by not-my-profile** [comment]
Thanks for your quick reply. I don't think this is a duplicate. #159 is as I understand about making the datetime in `toml::value::Value` accessible. I am however talking about directly using toml's `Deserializer` with a `serde::de::Deserialize` implementation from another crate, in which case there would be no `toml::value::Value` involved.

I don't think that changing the interfaces of any types would be necessary.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
