### ISSUE TITLE
What is the way to serialise strings with double quotes instead of single quotes?

### ISSUE THREAD

**Issue by P-E-Meunier** [toml-rs/toml-rs#432]
Single quotes are slightly inconvenient when the text inside is mostly English, and contains no escape sequence.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
