### ISSUE TITLE
This crate can add `no_std` support

### ISSUE THREAD

**Issue by ghost** [toml-rs/toml-rs#433]
All of this crate's necessary dependencies, `indexmap` and `serde`, can be used without `std`. Also, most parts of this crate can be done using `core`, `alloc` and `hashbrown`. If this crate can be `no_std`, it will improve a lot.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
