### ISSUE TITLE
Pub span constructor?

### ISSUE THREAD

**Issue by gilescope** [toml-rs/toml-rs#436]
I was trying to add spans to cargo (for line numbers on `Cargo.toml` errors) but it does some dependency replacements and I can't construct a Spanned myself. Ideally I want to be able to map a `Spanned<T>` into a `Spanned<U>` so there's more information but the span info is still retained. I can do it by copying all the code into the cargo crate and reimplementing Spanned but that's less than ideal. I'm a bit stuck with Spanned being as locked down as it is. 

I can wrap a `TomlDependency` into a `Spanned<TomlDependency>` and it all seems ok except the map_dependency function where I need to either map a Spanned value or create a new one:

https://github.com/rust-lang/cargo/blob/d555e49abee3e68036402f89e31f208a793cace1/src/cargo/util/toml/mod.rs#L1051

Suggestions welcome...

**Comment by gilescope** [comment]
Hang on, maybe I can clone a span and then call `get_mut()` and then `std::mem::swap(` the reference.... it's a hack and I'd prefer a pub constructor but it will keep me going...

**Comment by alexcrichton** [comment]
I think it's fine for `Spanned` to either have helper methods or a more "raw" constructor

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
