### ISSUE TITLE
Serializing a toml::Value produces invalid TOML

### ISSUE THREAD

**Issue by jgallagher** [toml-rs/toml-rs#446]
If I construct this table using just `toml::value::*` types:

```rust
    let mut table = Table::default();
    table.insert("foo".to_string(), Value::Integer(10));

    let mut array = Array::default();
    array.push(Value::Table(table));
    array.push(Value::String("bar".to_string()));

    let mut table = Table::default();
    table.insert("top".to_string(), Value::Array(array));
```

I believe (?) it should be a valid TOML structure; e.g.,

```rust
    assert_eq!(Value::Table(table), toml::toml! {
        top = [
            { foo = 10 },
            "bar",
        ]
    });
```

passes. However, serializing it via `to_string()` or `to_vec()` produces

```toml
[[top]]
foo = 10
, "bar"
```

which does not appear to be valid TOML (and the crate can't parse it). I'm not sure if it's possible to serialize this structure correctly without inline tables, which I know aren't supported yet. Should this fail to serialize, or is there a way for it to be serialized correctly without them?

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
