### ISSUE TITLE
Feature Request: ErrorInner struct fields be public

### ISSUE THREAD

**Issue by Ziris85** [toml-rs/toml-rs#448]
Hello,

Hoping this is just a simple request, but was writing a program using this crate and was trying to write some friendly error messaging around this and found that the "message" field in the ErrorInner struct was private, so I couldn't access its contents directly. Would appreciate if that (and perhaps all?) fields in that struct be made public so they can be directly referenced.

Thanks!

**Comment by TKGgunter** [comment]
I would also like this feature. Is there a reason why the library was not originally constructed in this manner? If there is no reason or the rational has been forgotten I'd be happy to submit a pr with this feature.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
