### ISSUE TITLE
Incorrect spans reported for toplevel tables

### ISSUE THREAD

**Issue by udoprog** [toml-rs/toml-rs#451]
In a document such as:

```toml
[key]
value = 42
```

The span being reported is `(0, 0)`.

See test:

```rust
#[derive(Deserialize)]
struct Foo {
    key: Spanned<HashMap<String, Spanned<toml::Value>>>,
}

let foo: Foo = toml::from_str("[key]\nvalue = 42")?;
assert_eq!(foo.key.span(), (0, 0));
```

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
