### ISSUE TITLE
Support DeserializeSeed

### ISSUE THREAD

**Issue by dhardy** [toml-rs/toml-rs#453]
Just creating an issue because I noticed this is missing functionality.

Support driving serialization with [`DeserializeSeed`](https://docs.rs/serde/latest/serde/de/trait.DeserializeSeed.html), e.g. [`serde_yaml::seed::from_reader_seed`](https://docs.rs/serde_yaml/latest/serde_yaml/seed/fn.from_reader_seed.html).

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
