### ISSUE TITLE
The decision to preserve order should probably not be a Cargo feature

### ISSUE THREAD

**Issue by cbiffle** [toml-rs/toml-rs#454]
Currently, `toml::Value`'s `Table` variant discards the order of the input data by default. This behavior can be changed by setting the `preserves_order` feature, which switches the implementation to an `IndexMap`.

Using a Cargo feature for this means that the decision is made across the entire dependency graph, such that a single crate requesting ordered tables will change the behavior for all other crates. Since the alphabetical ordering of `Table` is exposed through iterators by default, it seems likely that crates will depend on it (and I have personally written at least one crate that depended on it by accident), but there's no way for them to express that requirement at the type level or in the build system -- so it can be silently broken by changes in distant dependencies.

It seems to me that `preserves_order` violates the "purely additive" notion of Cargo features.

I'm not entirely sure what the right alternative is, though, the way the crate is structured. For now, we're probably going to fork the crate into a variant that has predictable order without the risk of subtly breaking our dependencies, but that's obviously not great.

**Comment by ehuss** [comment]
> express that requirement ... in the build system

Maybe I'm confused by what is meant here, but that requirement can be expressed by setting the feature.

```toml
[dependencies]
toml = { version = "0.5", features = ["preserve_order"] }
```

> It seems to me that `preserves_order` violates the "purely additive" notion of Cargo features.

Although it changes behavior, it changes behavior in an additive fashion. I don't think there is a reasonable expectation that code relies on random HashMap ordering. Adding preserve_order adds the expectation that it is preserved, and that does not interfere with code that works when it is unset.

**Comment by cbiffle** [comment]
> I don't think there is a reasonable expectation that code relies on random HashMap ordering.

The two ordering options exposed by this crate are sorted by key, and insertion order. HashMap isn't one of them.

It's pretty easy to write code that implicitly depends on sorted keys -- we've had it happen twice in the past few months. It's also pretty easy to write code that sets `preserve_order` and expects insertion order. The issue is when these two pieces of code (perhaps from different authors) get combined into one binary -- the first one breaks for reasons that are difficult to diagnose. (Or, better yet, when they are compiled into _different_ binaries but manipulate the same data...with different results due to separate feature resolution.)

> Maybe I'm confused by what is meant here, but that requirement can be expressed by setting the feature.

Right, the feature, in the build system. As opposed to expressing the requirement at type level, in the program, where it can't be implicitly changed by a distant dependency.

It might help to explain how this is being used.

In our build system for one of our operating systems, assembly of a firmware image is driven by a TOML configuration file. There are portions of the file that are defined by a common schema, and then portions that can include application-specified metadata. (This is roughly analogous to the `package.metadata` key in Cargo.) The common schema portion is defined by a struct using serde, with the extensible portion stuffed into it using a `toml::Value` [here](https://github.com/oxidecomputer/hubris/blob/740c61bfbaeb70005cabe840b7fe56aa4fa90a1b/build/xtask/src/main.rs#L148).

At that point, we have already lost information from the file -- specifically, ordering of table keys. Which also means ordering of top-level tables. This is fine for 90% of our use cases, but we had a case where we wanted the ordering in the file to be preserved to convey both name and index (in this case, for reasons of backwards compatibility and order stability in the face of name changes). At that point we were in a pickle -- we could set `preserve_order`, but Cargo feature resolution would turn that on for every TOML user across our entire dependency graph. We had other code that turned out to be implicitly expecting sorted keys, which caused me to suspect that we're not the only ones -- that there might be other code we're getting from crates.io that also made that assumption and could be broken by this feature being turned on.

What we've done for now is to [fork just the `toml::Value` part of this crate](https://github.com/oxidecomputer/ordered-toml) into a version that has permanently defined order, and can be deserialized by `toml-rs`. We use this in any case where we need order preserved on an arbitrary `Value`. No code consuming an `ordered_toml::Value` will assume sorted order, because it never produces sorted order.

Which is why I asserted that this feature is not purely additive:

> Although it changes behavior, it changes behavior in an additive fashion.

Removing sorting is not additive. If the default storage were a HashMap with keyed randomized order, there'd be an argument here, but it isn't. Much like how there was a lot of code in the Rust ecosystem depending on struct fields being laid out in declaration order in the days before struct layout optimization (or order randomization in debug builds), I expect there is other code in the ecosystem depending on sorted keys in `toml::Value` that can be broken by feature resolution. Might be interesting to flip the feature and do a crater run -- though our code wouldn't be included.

**Comment by ehuss** [comment]
Ah, apologies, I forgot that it was using a btree instead of a hashmap.

It sounds like forking `Value` was probably the right way to go.  Similar to the discussion at https://github.com/serde-rs/json/issues/225, I think keeping `Value` simple and easy-to-use is probably a priority over making it flexible for different scenarios. I understand that whether or not the feature is enabled can break code expecting one behavior or another, and that doesn't entirely honor the additive nature of features.

**Comment by cbiffle** [comment]
I agree. So, which behavior of `Value` is simple and easy to use, and should the other be removed?

I would argue that throwing away information from the input files (i.e. automatically sorting tables) is a poor default, and `IndexMap` should be the default-and-only. Others might not agree. :-) But either way, I think this should probably not be under control of a Cargo feature, and suggest that removing the feature would be good.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
