### ISSUE TITLE
`toml::ser::tables_last` (intentionally) doesn't work recursively.

### ISSUE THREAD

**Issue by dtomvan** [toml-rs/toml-rs#458]
I am writing a program that quickly converts a JSON file to TOML. I have already filtered out `null` and I'm using `toml::ser::tables_last`, but I still get a `ValueAfterTable` error. This is my code:
```rust
    let deserialized: Map<String, Value> =
        serde_json::from_str(&data).expect("This isn't valid JSON.");
    let deserialized: Map<String, Value> = deserialized
        .into_iter()
        .filter(|x| !x.1.is_null())
        .collect();
    let mut toml = String::new();
    toml::ser::tables_last(
        &deserialized,
        Serializer::new(&mut toml)
            .pretty_array(true)
            .pretty_string(true)
            .pretty_array_indent(4)
            .pretty_string_literal(true)
            .pretty_array_trailing_comma(true),
    )
    .expect("Could not serialize to toml");
```

Maybe this happens because `tables_last` doesn't operate recursively, but maybe I'm using the function incorrectly. I do not necessarily know the format the JSON is going to be in, so deserializing to a struct won't work.

See also: #142

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
