### ISSUE TITLE
New Maintainers

### ISSUE THREAD

**Issue by alexcrichton** [toml-rs/toml-rs#460]
I personally no longer have the time or energy to maintain this crate. I believe this is still pretty widely used as the default TOML implementation for Rust, however, so it'd be good to keep this maintained. I'm opening this to see if there is another who is willing to take over ownership and maintenance of this crate. In the meantime I will not be maintaining this crate other than if a security issue arises.

**Comment by thomcc** [comment]
I can maintain it if nobody wants to, but largely I would probably just be reviewing/merging PRs and needed to keep up with changes to the TOML spec. That is, it wouldn't be *that* active of maintenance (although I probably would make some changes like no_std support and such).

**Comment by djc** [comment]
I can also help with (mostly passively) maintaining this.

**Comment by decathorpe** [comment]
I'm already maintaining the Fedora Linux RPM package for this crate, so I can help maintaining the "upstream" project, as well.

**Comment by epage** [comment]
@alexcrichton what if we moved `toml_edit::easy` into `toml`?

As task I've been meaning to get to is to restructure `toml_edit` so a subset can more easily show up in public APIs, like `cargo_metadata` including `toml`.  One possible route for that is to split `toml_edit::easy` out into its own crate and not expose any `toml_edit` types.

The downside being that `toml_edit::easy` has a ceiling on how fast it can get due to the format-preserving core its built on, even if the performance right now is roughly on par with `toml`.

**Comment by Pyzyryab** [comment]
@alexcrichton are you still looking for someone that wants to take care about the project?

**Comment by alexcrichton** [comment]
Yes I ostensibly am still looking for an interested maintainer. At this point though I would prefer to just hand the reins to someone else and not really be that involved. I'd rather not need to work in an advisory status where I still have to double-check on changes or such.

**Comment by tshepang** [comment]
one option is donating to rust-lang org... libs team is forming a team to take care of such central crates

**Comment by tarcieri** [comment]
@alexcrichton any thoughts on @epage’s proposal to allow the API-compatible `toml_edit::easy` implementation to be published as the `toml` crate?

**Comment by alexcrichton** [comment]
I don't personally know enough about `toml_edit::easy` to make a judgement call on that, and I'm not really in a position to do that myself. I basically need someone to step up and take the lead on this. If @epage you'd like to do that I'm happy to transfer the crate to you.

**Comment by epage** [comment]
Yes, I'd be willing to take that on. 

Before changing out the guts, I feel like a once-over will be needed to double check it meets toml-rs's quality needs.

https://github.com/ordian/toml_edit/issues/327 might also be a blocker for swapping over; I haven't decided yet and am open for input.

For anyone else interested in the level of compatibility, these are the two PRs for switching cargo from toml to toml_edit::easy
- https://github.com/rust-lang/cargo/pull/9932
- https://github.com/rust-lang/cargo/pull/10086

**Comment by alexcrichton** [comment]
Ok, thanks! When you're satisfied I'm happy to add you to crates.io and leave a tombstone in this repository's README or similar.

**Comment by epage** [comment]
@alexcrichton if a gradual approach is fine with you've, we've gone ahead and [merged the toml-rs repo into toml_edit](https://github.com/toml-rs/toml_edit/pull/336) and created https://github.com/toml-rs for hosting this and the rust wrapper around toml-test.

**Comment by alexcrichton** [comment]
Thanks! Would you like me to transfer this repo to that org for posterity or just update the README?

**Comment by epage** [comment]
Either works for me

**Comment by alexcrichton** [comment]
Ok I've sent a transfer request for this repo to you and I've added you to crates.io

**Comment by epage** [comment]
Looks like we're all good now; closing this out
