### ISSUE TITLE
Can't deserialize a `HashMap` with enum keys from a toml string

### ISSUE THREAD

**Issue by e-rhodes** [toml-rs/toml-rs#469]
Deserializing a `HashMap` with enum keys fails when reading from a `toml` string.

In particular, with this setup:
```rust
#[derive(Debug, Deserialize, Hash, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
enum Key { ... }
```

Deserializing into my type from a `toml::Value` works fine:

```rust
let res: HashMap<Key, String> = data.try_into().unwrap(); // where data is a toml::Value from toml!()
```

However, I'm reading the configuration from a file, so I just have a string.

As a workaround, this works:
```rust
let res: HashMap<Key, String> = data_string
    .parse::<toml::Value>()
    .unwrap()
    .try_into()
    .unwrap();
```

and this works too:
    
```rust
#[derive(Debug, Deserialize)]
struct Outer {
    #[serde(flatten)]
    inner: HashMap<Key, String>,
}
let Outer { inner: res } = toml::from_str(&data_string).unwrap();
```

But this does not:

```rust
let res: HashMap<Key, String> = toml::from_str(&data_string).unwrap();
```

May be related to #212, but doesn't break the only-string-keys restriction of the TOML format.

I'd like to be able to use any type that implements `Deserialize` as a key here ideally!

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c4556d2850bd1c13fa388f9dd6fc36db)

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
