### ISSUE TITLE
Value method (like get()) to access sub-paths 

### ISSUE THREAD

**Issue by aawsome** [toml-rs/toml-rs#474]
I'd like to have a method on Values to access sub-paths, e.g. in a  "."-style like this

```
let value = toml::from_str(string)?;
let sub_value = value.get_path("section.subsection");
```
I think this is really convenient when accessing configurations.

So far I implemented this on a newtype like this:
```
struct MyValue(Value);
impl MyValue{
  fn get_path(&self, path: &str) -> Option<&Value> {
        path
            .split('.')
            .fold(Some(&self.0), |acc, x| acc.and_then(|value| value.get(x)))
    }
}
```

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
