### ISSUE TITLE
Serializing nested arrays of tables gives a wrong result

### ISSUE THREAD

**Issue by Aloxaf** [toml-rs/toml-rs#475]
```rust
fn main() {
    let x = toml::toml! {
        a = [[ {b = 1} ]]
    };
    println!("{}", toml::to_string(&x).unwrap());
}
```

I test it on [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=943a343f41f4fc5908c17dd0ee0ed50f), and result is follows:

```
[[a]]
b = 1
]
```

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
