### ISSUE TITLE
Editing the contents of Tables and Values

### ISSUE THREAD

**Issue by ebkalderon** [toml-rs/toml-rs#83]
I want to manipulate the contents of an existing TOML file. I started with something like this:

``` rust
// The contents of the file. Let's pretend I read them from disk.
let toml = "
[test]
key = \"value\"
otherkey = \"othervalue\"
";

let mut table = toml::Parser::new(toml).parse().unwrap();

// Remove the "key" Item from the "test" Table.
table.get_mut("test").unwrap().as_table().unwrap().remove("key").unwrap();

// Turn the modified Table back into a String, ready to write back to the file.
let modified = toml::encode_str(&toml::Value::Table(table));
```

However, according to the documentation and the following error message, the Value struct's `as_*()` methods can only return immutable structs. Am I missing something? Is there another, easier way to go about this? If not, I seriously recommend manipulating Values/Tables as a feature.

Thanks in advance.

**Comment by alexcrichton** [comment]
Yeah unfortunately this library doesn't support this use case very well right now. I'm hoping to update it at some point in the future to have a more feature-ful AST (with a different API) to allow preserving components such as whitespace and comments.

That being said it's pretty far off, so I wouldn't hold your breath any time soon :(

**Comment by alexcrichton** [comment]
I've rewritten the parser in https://github.com/alexcrichton/toml-rs/pull/137 and the lowest layer (tokenization) supports whitespace/comments and otherwise preserving the original source where appropriate, but beyond that I haven't made much progress on this.

**Comment by sedrik** [comment]
Do you have a work in progress that we can look at and contribute to? I think the idea of parsing into a AST that can then later on be serialized into different formats (among others JSON and back to TOML) is the best approach.

**Comment by alexcrichton** [comment]
Nah unfortunately not much more that #137. The `src/tokens.rs` is likely the starting point (as it preserves *everything*), but much more support is going to be needed.

**Comment by epage** [comment]
Maintenance of this crate has moved to the https://github.com/toml-rs/toml repo.  As a heads up, we plan to move `toml` to be on top of `toml_edit`, see https://github.com/toml-rs/toml/issues/340.

Closing this out.  If this is still a problem, feel free to recreate this issue in the new repo.
